spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/university"
    username:
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  servlet:
    context-path: /university-api
